/**
 * =============================================================================
 * glad.c - OpenGL Function Loader Implementation
 * =============================================================================
 * This file implements the GLAD loader that loads OpenGL function pointers
 * at runtime. In a real project, this would be generated by GLAD.
 * 
 * How it works:
 * 1. gladLoadGLLoader() is called with a function that can look up
 *    OpenGL function addresses (e.g., glfwGetProcAddress)
 * 2. For each OpenGL function we need, we call the loader to get its address
 * 3. We store these addresses in function pointers
 * 4. When we call glSomething(), it goes through the function pointer
 * =============================================================================
 */

#include <glad/glad.h>

// Version check variable
int GLAD_GL_VERSION_3_3 = 0;

// =============================================================================
// Function Pointer Definitions
// =============================================================================
// These are the actual function pointer variables. They start as NULL and
// are filled in by gladLoadGLLoader().

// State management
PFNGLCLEARCOLORPROC glClearColor = NULL;
PFNGLCLEARPROC glClear = NULL;
PFNGLVIEWPORTPROC glViewport = NULL;
PFNGLENABLEPROC glEnable = NULL;
PFNGLDISABLEPROC glDisable = NULL;
PFNGLBLENDFUNCPROC glBlendFunc = NULL;
PFNGLDEPTHFUNCPROC glDepthFunc = NULL;
PFNGLCULLFACEPROC glCullFace = NULL;
PFNGLFRONTFACEPROC glFrontFace = NULL;
PFNGLDEPTHMASKPROC glDepthMask = NULL;
PFNGLGETERRORPROC glGetError = NULL;
PFNGLGETSTRINGPROC glGetString = NULL;

// Shader functions
PFNGLCREATESHADERPROC glCreateShader = NULL;
PFNGLSHADERSOURCEPROC glShaderSource = NULL;
PFNGLCOMPILESHADERPROC glCompileShader = NULL;
PFNGLGETSHADERIVPROC glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = NULL;
PFNGLDELETESHADERPROC glDeleteShader = NULL;
PFNGLCREATEPROGRAMPROC glCreateProgram = NULL;
PFNGLATTACHSHADERPROC glAttachShader = NULL;
PFNGLLINKPROGRAMPROC glLinkProgram = NULL;
PFNGLGETPROGRAMIVPROC glGetProgramiv = NULL;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = NULL;
PFNGLUSEPROGRAMPROC glUseProgram = NULL;
PFNGLDELETEPROGRAMPROC glDeleteProgram = NULL;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = NULL;

// Uniform functions
PFNGLUNIFORM1IPROC glUniform1i = NULL;
PFNGLUNIFORM1FPROC glUniform1f = NULL;
PFNGLUNIFORM2FPROC glUniform2f = NULL;
PFNGLUNIFORM3FPROC glUniform3f = NULL;
PFNGLUNIFORM4FPROC glUniform4f = NULL;
PFNGLUNIFORM3FVPROC glUniform3fv = NULL;
PFNGLUNIFORM4FVPROC glUniform4fv = NULL;
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv = NULL;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = NULL;

// VAO functions
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = NULL;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray = NULL;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = NULL;

// Buffer functions
PFNGLGENBUFFERSPROC glGenBuffers = NULL;
PFNGLBINDBUFFERPROC glBindBuffer = NULL;
PFNGLBUFFERDATAPROC glBufferData = NULL;
PFNGLBUFFERSUBDATAPROC glBufferSubData = NULL;
PFNGLDELETEBUFFERSPROC glDeleteBuffers = NULL;

// Vertex attribute functions
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = NULL;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = NULL;

// Drawing functions
PFNGLDRAWARRAYSPROC glDrawArrays = NULL;
PFNGLDRAWELEMENTSPROC glDrawElements = NULL;

// Texture functions
PFNGLGENTEXTURESPROC glGenTextures = NULL;
PFNGLBINDTEXTUREPROC glBindTexture = NULL;
PFNGLTEXIMAGE2DPROC glTexImage2D = NULL;
PFNGLTEXPARAMETERIPROC glTexParameteri = NULL;
PFNGLGENERATEMIPMAPPROC glGenerateMipmap = NULL;
PFNGLACTIVETEXTUREPROC glActiveTexture = NULL;
PFNGLDELETETEXTURESPROC glDeleteTextures = NULL;

// Polygon mode
PFNGLPOLYGONMODEPROC glPolygonMode = NULL;

// =============================================================================
// Loader Implementation
// =============================================================================

/**
 * Load a single OpenGL function.
 * Returns NULL if not found (shouldn't happen for core functions).
 */
static void* load_gl_func(GLADloadproc load, const char* name) {
    void* result = load(name);
    return result;
}

/**
 * Load all OpenGL functions.
 * Returns 1 on success, 0 on failure.
 */
int gladLoadGLLoader(GLADloadproc load) {
    if (load == NULL) {
        return 0;
    }
    
    // Load state management functions
    glClearColor = (PFNGLCLEARCOLORPROC)load_gl_func(load, "glClearColor");
    glClear = (PFNGLCLEARPROC)load_gl_func(load, "glClear");
    glViewport = (PFNGLVIEWPORTPROC)load_gl_func(load, "glViewport");
    glEnable = (PFNGLENABLEPROC)load_gl_func(load, "glEnable");
    glDisable = (PFNGLDISABLEPROC)load_gl_func(load, "glDisable");
    glBlendFunc = (PFNGLBLENDFUNCPROC)load_gl_func(load, "glBlendFunc");
    glDepthFunc = (PFNGLDEPTHFUNCPROC)load_gl_func(load, "glDepthFunc");
    glCullFace = (PFNGLCULLFACEPROC)load_gl_func(load, "glCullFace");
    glFrontFace = (PFNGLFRONTFACEPROC)load_gl_func(load, "glFrontFace");
    glDepthMask = (PFNGLDEPTHMASKPROC)load_gl_func(load, "glDepthMask");
    glGetError = (PFNGLGETERRORPROC)load_gl_func(load, "glGetError");
    glGetString = (PFNGLGETSTRINGPROC)load_gl_func(load, "glGetString");
    
    // Load shader functions
    glCreateShader = (PFNGLCREATESHADERPROC)load_gl_func(load, "glCreateShader");
    glShaderSource = (PFNGLSHADERSOURCEPROC)load_gl_func(load, "glShaderSource");
    glCompileShader = (PFNGLCOMPILESHADERPROC)load_gl_func(load, "glCompileShader");
    glGetShaderiv = (PFNGLGETSHADERIVPROC)load_gl_func(load, "glGetShaderiv");
    glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)load_gl_func(load, "glGetShaderInfoLog");
    glDeleteShader = (PFNGLDELETESHADERPROC)load_gl_func(load, "glDeleteShader");
    glCreateProgram = (PFNGLCREATEPROGRAMPROC)load_gl_func(load, "glCreateProgram");
    glAttachShader = (PFNGLATTACHSHADERPROC)load_gl_func(load, "glAttachShader");
    glLinkProgram = (PFNGLLINKPROGRAMPROC)load_gl_func(load, "glLinkProgram");
    glGetProgramiv = (PFNGLGETPROGRAMIVPROC)load_gl_func(load, "glGetProgramiv");
    glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)load_gl_func(load, "glGetProgramInfoLog");
    glUseProgram = (PFNGLUSEPROGRAMPROC)load_gl_func(load, "glUseProgram");
    glDeleteProgram = (PFNGLDELETEPROGRAMPROC)load_gl_func(load, "glDeleteProgram");
    glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)load_gl_func(load, "glGetUniformLocation");
    
    // Load uniform functions
    glUniform1i = (PFNGLUNIFORM1IPROC)load_gl_func(load, "glUniform1i");
    glUniform1f = (PFNGLUNIFORM1FPROC)load_gl_func(load, "glUniform1f");
    glUniform2f = (PFNGLUNIFORM2FPROC)load_gl_func(load, "glUniform2f");
    glUniform3f = (PFNGLUNIFORM3FPROC)load_gl_func(load, "glUniform3f");
    glUniform4f = (PFNGLUNIFORM4FPROC)load_gl_func(load, "glUniform4f");
    glUniform3fv = (PFNGLUNIFORM3FVPROC)load_gl_func(load, "glUniform3fv");
    glUniform4fv = (PFNGLUNIFORM4FVPROC)load_gl_func(load, "glUniform4fv");
    glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)load_gl_func(load, "glUniformMatrix3fv");
    glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)load_gl_func(load, "glUniformMatrix4fv");
    
    // Load VAO functions
    glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)load_gl_func(load, "glGenVertexArrays");
    glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)load_gl_func(load, "glBindVertexArray");
    glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)load_gl_func(load, "glDeleteVertexArrays");
    
    // Load buffer functions
    glGenBuffers = (PFNGLGENBUFFERSPROC)load_gl_func(load, "glGenBuffers");
    glBindBuffer = (PFNGLBINDBUFFERPROC)load_gl_func(load, "glBindBuffer");
    glBufferData = (PFNGLBUFFERDATAPROC)load_gl_func(load, "glBufferData");
    glBufferSubData = (PFNGLBUFFERSUBDATAPROC)load_gl_func(load, "glBufferSubData");
    glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)load_gl_func(load, "glDeleteBuffers");
    
    // Load vertex attribute functions
    glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)load_gl_func(load, "glVertexAttribPointer");
    glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)load_gl_func(load, "glEnableVertexAttribArray");
    glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)load_gl_func(load, "glDisableVertexAttribArray");
    
    // Load drawing functions
    glDrawArrays = (PFNGLDRAWARRAYSPROC)load_gl_func(load, "glDrawArrays");
    glDrawElements = (PFNGLDRAWELEMENTSPROC)load_gl_func(load, "glDrawElements");
    
    // Load texture functions
    glGenTextures = (PFNGLGENTEXTURESPROC)load_gl_func(load, "glGenTextures");
    glBindTexture = (PFNGLBINDTEXTUREPROC)load_gl_func(load, "glBindTexture");
    glTexImage2D = (PFNGLTEXIMAGE2DPROC)load_gl_func(load, "glTexImage2D");
    glTexParameteri = (PFNGLTEXPARAMETERIPROC)load_gl_func(load, "glTexParameteri");
    glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)load_gl_func(load, "glGenerateMipmap");
    glActiveTexture = (PFNGLACTIVETEXTUREPROC)load_gl_func(load, "glActiveTexture");
    glDeleteTextures = (PFNGLDELETETEXTURESPROC)load_gl_func(load, "glDeleteTextures");
    
    // Load polygon mode
    glPolygonMode = (PFNGLPOLYGONMODEPROC)load_gl_func(load, "glPolygonMode");
    
    // Check that essential functions were loaded
    if (glClear == NULL || glCreateShader == NULL || glGenVertexArrays == NULL) {
        return 0;
    }
    
    // Mark OpenGL 3.3 as available
    GLAD_GL_VERSION_3_3 = 1;
    
    return 1;
}
